const assert = require('node:assert/strict')
const { click, clickText, command, evaluate, input, key, panesFor, q, reload, report, scenario, screenshot, seedBoard, useLocalModel, wait, until, delay, size, ui } = require('../harness.cjs')
const show = 'button[aria-label="Ver actividad del turno"]'
const hide = 'button[aria-label="Ocultar actividad del turno"]'
const body = '[data-activity-body]'
const scroller = '.conversation-enter > .overflow-y-auto'
const pending = () => fetch(new URL('/__pending?lane=main', ui.model)).then(r => r.json())
async function release() {
  await until(async () => await pending() > 0, 'model waits for next step')
  assert.equal(await fetch(new URL('/__release?lane=main', ui.model)).then(r => r.json()), true)
}
async function send(prefix, message) {
  await input(prefix + ' .composer-surface textarea', message)
  await click(prefix + ' .composer-surface button[aria-label="Enviar mensaje"]')
}
scenario(async () => {
  await useLocalModel()
  const ids = []
  for (const title of ['Actividad A', 'Actividad B']) ids.push((await command('session_create', { chat: true, title })).session.id)
  await seedBoard({ boardId: 'activity', panes: panesFor(ids), focusedPaneId: 'pane_0' })
  await click('.view-switcher button[aria-label="Normal"]')
  await clickText('Actividad A', 'aside button', { includes: true })
  await send('', 'Revisa los archivos locales paso a paso')
  await release()
  await until(async () => await pending() > 0, 'first progress classified')
  await wait(`Boolean(${q(show)})`)
  assert.equal(await evaluate(`Boolean(${q(body)})`), false)
  assert.equal(await evaluate(`document.body.innerText.includes('PROGRESO 1')`), false)
  await screenshot('normal-live-folded')
  await click(show)
  await wait(`document.body.innerText.includes('PROGRESO 1')`)
  // Keep the user's instruction at its chronological boundary.
  await click('.composer-surface textarea')
  await input('.composer-surface textarea', 'INSTRUCCIÓN INTERCALADA: conserva todos los detalles')
  await key('Enter')
  await wait(`document.body.innerText.includes('INSTRUCCIÓN INTERCALADA')`)
  await release()
  await until(async () => await pending() > 0, 'second progress classified')
  await wait(`document.body.innerText.includes('Actividad anterior')`)
  assert(await evaluate(`Boolean(${q(hide)})`), 'the manually opened previous segment stays open')
  await release()
  await until(async () => await pending() > 0, 'third progress classified after steering was applied')
  await evaluate(`${q(show)}.click()`)
  await wait(`document.querySelectorAll(${JSON.stringify(hide)}).length===2`)
  for (let step = 4; step <= 24; step++) await release()
  await until(async () => await pending() > 0, 'final response pending')
  assert.equal(await evaluate(`document.querySelectorAll(${JSON.stringify(hide)}).length`), 2, 'both segments stay open through subsequent activity')
  const nodesDuringExecution = await evaluate(`document.querySelectorAll('*').length`)
  // Nested inspection survives a switch of view; no Engine reload.
  await evaluate(`(() => {const d=document.querySelector('[data-activity-body] details');d.open=true})()`)
  await click('.view-switcher button[aria-label^="Boards"]')
  const a = '[data-pane-id="pane_0"]'
  const b = '[data-pane-id="pane_1"]'
  await wait(`${q(a)}.querySelectorAll(${JSON.stringify(hide)}).length===2`)
  assert(await evaluate(`${q(a + ' [data-activity-body] details')}.open`), 'inner details restored in Boards')
  await release()
  await wait(`${q(a)}.innerText.includes('RESULTADO COMPLETO')`)
  await wait(`${q(a)}.innerText.includes('Ha trabajado durante')`)
  assert.equal(await evaluate(`${q(a)}.querySelectorAll('[data-testid="turn-result"]').length`), 1)
  assert.equal(await evaluate(`${q(a)}.querySelectorAll(${JSON.stringify(hide)}).length`), 2)
  const nodesOpen = await evaluate(`${q(a)}.querySelectorAll('*').length`)
  await screenshot('boards-final-open')
  const turnId = await evaluate(`${q(a + ' [data-testid="turn-result"]')}.dataset.turnId`)
  await evaluate(`window.dispatchEvent(new CustomEvent('rinari:reveal-turn',{detail:{sessionId:${JSON.stringify(ids[0])},turnId:${JSON.stringify(turnId)}}}))`)
  await wait(`Math.abs(${q(a + ' [data-testid="turn-result"]')}.getBoundingClientRect().top-${q(a + ' ' + scroller)}.getBoundingClientRect().top)<8`)

  // Collapse from below a large body: the control remains visible and focused.
  const controls = await evaluate(`${q(a)}.querySelectorAll(${JSON.stringify(hide)}).length`)
  for (let i = 0; i < controls; i++) await click(a + ' ' + hide)
  assert.equal(await evaluate(`${q(a)}.querySelectorAll(${JSON.stringify(body)}).length`), 0)
  assert(await evaluate(`${q(a)}.innerText.includes('Párrafo final 35')`))
  assert(await evaluate(`(()=>{const b=document.activeElement,r=b.getBoundingClientRect(),v=${q(a + ' ' + scroller)}.getBoundingClientRect();return r.top>=v.top-2&&r.bottom<=v.bottom+2})()`), 'collapse keeps the focused header visible')
  const nodesClosed = await evaluate(`${q(a)}.querySelectorAll('*').length`)
  assert(nodesClosed < nodesOpen, 'folding actually unmounts activity DOM')
  const expandTwoFramesMs = await evaluate(`new Promise(resolve=>{const start=performance.now(),b=${q(a + ' ' + show)};b.focus();b.click();requestAnimationFrame(()=>requestAnimationFrame(()=>resolve(performance.now()-start)))})`)
  ui.win.focus()
  await key('Space')
  await wait(`document.activeElement?.getAttribute('aria-expanded')==='false'`)
  ui.win.show()
  if (ui.win.isMinimized()) ui.win.restore()
  await delay(300)
  await size(1000, 760)
  await ui.win.webContents.debugger.attach('1.3')
  await ui.win.webContents.debugger.sendCommand('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] })
  assert(await evaluate(`matchMedia('(prefers-reduced-motion: reduce)').matches`))
  await screenshot('boards-narrow-reduced-motion')
  await ui.win.webContents.debugger.detach()
  await size(1500, 900)
  // The neighbour has its own execution and disclosure state.
  await send(b, 'Prueba del fallo recuperable')
  await release()
  await wait(`${q(b)}.innerText.includes('El turno falló')`, 60000)
  assert(await evaluate(`Boolean(${q(b + ' [role="alert"]')})`))
  await screenshot('boards-failure-outside')
  await send(b, 'Continúa después del error')
  await release()
  await wait(`${q(b)}.innerText.includes('RESPUESTA PARA EL PANEL VECINO')`)
  // A reload reconstructs the real persisted timeline, but UI disclosure is session-memory only.
  await reload()
  await click('.view-switcher button[aria-label^="Boards"]')
  await wait(`Boolean(${q(a + ' ' + show)})`)
  assert.equal(await evaluate(`${q(a)}.querySelectorAll(${JSON.stringify(body)}).length`), 0)
  assert(await evaluate(`${q(a)}.innerText.includes('RESULTADO COMPLETO')`))
  await evaluate(`for(const el of document.querySelectorAll(${JSON.stringify(scroller)})){el.scrollTop=0;el.dispatchEvent(new Event('scroll'))}`)
  await screenshot('history-restored')
  if (ui.keep) await fetch(new URL('/__resume?lane=main', ui.model))
  report({ nodesDuringExecution, nodesOpen, nodesClosed, expandTwoFramesMs, passed: ['starts folded', 'public progress classified inside', 'steering visible in chronological segments', 'manual opening survives completion and Normal/Boards', 'nested inspection restored', 'complete final outside activity', 'keyboard', 'narrow Boards', 'reduced motion', 'provider failure outside and new turn recovery', 'history replay starts folded'] })
}, { width: 1500, height: 900 })
