// @generated by scripts/generate-protocol.mjs — DO NOT EDIT.
// Source: Rinari Engine Protocol v1 (sha256:061e0e7e7dc09763f0be39ad086eb7704cf8f916424023e771bb17f58e72a168)

export const ENGINE_METHODS = [
  "engine.info",
  "runtime.snapshot.get",
  "session.move",
  "workspace.file.read",
  "workspace.file.watch",
  "workspace.file.unwatch",
  "workspace.preview.start",
  "workspace.preview.status",
  "workspace.preview.stop",
  "question.list",
  "question.resolve",
  "session.list",
  "session.get",
  "session.create",
  "session.open",
  "session.rename",
  "session.archive",
  "session.restore",
  "session.pin",
  "session.delete",
  "session.fork",
  "session.history",
  "session.mode.set",
  "session.model.set",
  "session.permission.get",
  "session.permission.set",
  "session.turn.start",
  "command.list",
  "target.list",
  "target.add",
  "operation.start",
  "operation.get",
  "operation.cancel",
  "session.turn.cancel",
  "session.turn.steer",
  "session.events",
  "session.timeline",
  "approval.resolve",
  "turn.changes.get",
  "turn.changes.review",
  "turn.changes.undo.preview",
  "turn.changes.undo",
  "project.list",
  "project.get",
  "project.add",
  "project.update",
  "project.remove",
  "project.list_recent",
  "project.open",
  "project.status",
  "project.intelligence",
  "project.trust",
  "project.changes",
  "project.diff",
  "provider.list",
  "provider.get",
  "provider.create",
  "provider.update",
  "provider.remove",
  "provider.test",
  "provider.discover",
  "provider.use",
  "model.list",
  "model.get",
  "model.add",
  "model.alias",
  "model.remove",
  "model.use",
  "model.discover",
  "model.discovery.start",
  "model.refresh",
  "model.test",
  "model.capabilities",
  "agent.list",
  "agent.config.get",
  "agent.config.set",
  "soul.list",
  "soul.get",
  "soul.create",
  "soul.update",
  "soul.remove",
  "soul.activate",
  "soul.get_effective",
  "session.soul.set",
  "session.soul.clear",
  "mcp.list",
  "mcp.get",
  "mcp.create",
  "mcp.remove",
  "mcp.enable",
  "mcp.disable",
  "mcp.test",
  "plugin.list",
  "plugin.get",
  "plugin.enable",
  "plugin.disable",
  "plugin.diagnostics",
  "skill.list",
  "skill.get",
  "skill.read",
  "skill.enable",
  "skill.disable",
  "skill.remove",
  "skill.write",
  "skill.import.scan",
  "skill.job.start",
  "skill.job.get",
  "skill.pending.list",
  "skill.pending.approve",
  "skill.pending.reject",
  "skill.revert",
  "skill.settings.get",
  "skill.settings.set",
  "tool.list",
  "policy.get",
  "task.tree",
  "task.get",
  "verification.latest",
  "verification.plan",
  "checkpoint.list",
  "checkpoint.show",
  "checkpoint.restore",
  "pty.start",
  "pty.write",
  "pty.resize",
  "pty.read",
  "pty.list",
  "pty.terminate",
  "pty.shells",
  "profile_bundle.list",
  "profile_bundle.get",
  "profile_bundle.create",
  "profile_bundle.remove",
  "profile_bundle.apply",
  "session.queue.add",
  "session.queue.list",
  "session.queue.clear",
  "session.queue.resume",
  "session.peer_group.set",
  "session.peer_group.get",
  "session.peer_group.revoke",
  "session.peer_message.list",
  "session.peer_message.cancel",
  "session.peer_message.forward",
  "session.branch",
  "workspace.file.search",
  "artifact.list",
  "artifact.read",
  "artifact.export",
  "context.get",
  "memory.list",
  "memory.search",
  "memory.get",
  "memory.remember",
  "memory.update",
  "memory.forget",
  "memory.candidates.list",
  "memory.candidate.resolve",
  "conversation.memory.status",
  "conversation.memory.exclude",
  "conversation.delete",
  "memory.ledger.export",
  "memory.ledger.import",
  "usage.get",
  "session.close",
  "channel.pending",
  "channel.resolve",
  "artifact.receive_image",
  "artifact.delete_media",
  "session.image_support",
  "artifact.media_list",
  "attachment.prepare",
  "attachment.preview",
  "attachment.prepare.start",
  "attachment.prepare.get",
  "attachment.prepare.cancel",
  "model.vision.set",
  "browser.view.get",
  "browser.context.get",
  "browser.context.prepare",
  "browser.control.set",
  "host.browser.register",
  "host.browser.unregister",
  "host.browser.reply",
  "host.browser.event",
  "workspace.process.list",
  "workspace.process.read",
  "workspace.process.stop",
  "vision.settings.get",
  "vision.settings.set",
  "context.settings.get",
  "context.settings.set",
  "context.compact",
  "context.status",
  "context.models",
  "flow.get",
  "provider.catalog.get",
  "provider.usage.get",
  "provider.diagnostics.get",
  "provider.auth.start",
  "provider.auth.get",
  "provider.auth.cancel",
  "provider.auth.logout",
  "schedule.list",
  "schedule.get",
  "schedule.create",
  "schedule.update",
  "schedule.delete",
  "schedule.runs",
  "schedule.run_now",
  "schedule.grant"
] as const
export type EngineMethod = (typeof ENGINE_METHODS)[number]

export const ENGINE_EVENTS = [
  "turn.started",
  "turn.completed",
  "turn.failed",
  "turn.cancelled",
  "host.browser.request",
  "browser.control.changed",
  "turn.stopped",
  "model.started",
  "model.content.delta",
  "model.content.completed",
  "model.completed",
  "model.failed",
  "tool.requested",
  "tool.started",
  "tool.output.delta",
  "tool.completed",
  "tool.failed",
  "tool.cancelled",
  "approval.requested",
  "approval.resolved",
  "approval.expired",
  "question.requested",
  "question.resolved",
  "question.expired",
  "session.moved",
  "governor.progress",
  "governor.nudge",
  "governor.compact",
  "governor.consolidate",
  "governor.stop",
  "usage.updated",
  "agent.started",
  "agent.completed",
  "agent.failed",
  "verification.started",
  "verification.completed",
  "verification.failed",
  "model.discovery.completed",
  "model.discovery.failed",
  "turn.changes.completed",
  "turn.changes.undo.started",
  "turn.changes.undo.completed",
  "turn.changes.undo.conflict",
  "workspace.changed",
  "workspace.file.changed",
  "channel.requested",
  "agent.activity",
  "vision.started",
  "vision.completed",
  "vision.failed",
  "vision.cancelled",
  "session.peer.group.updated",
  "session.peer.message",
  "session.peer.message.updated",
  "flow.invalidated",
  "provider.usage.updated",
  "provider.auth.updated",
  "skill.job.completed",
  "skill.job.failed",
  "skill.learned",
  "schedule.changed",
  "schedule.run.started",
  "schedule.run.needs_you",
  "schedule.run.completed",
  "schedule.proposed",
  "steer.applied",
  "steer.returned"
] as const
export type EngineEventName = (typeof ENGINE_EVENTS)[number]

export interface Attachment {
  id: string
  path: string
  name: string
  mime_type?: string | null
  size?: number | null
  source: "native" | "workspace"
  data_url?: string | null
  uri?: string | null
  sha256?: string | null
  kind?: string | null
  derived_uri?: string | null
  status?: string | null
  ocr?: boolean | null
  truncated?: boolean | null
  error?: string | null
  page_range?: string | null
  visual_pages?: Array<number> | null
  images?: Array<Record<string, unknown>> | null
  warning?: string | null
  content_type?: string | null
}

export interface SessionSummary {
  id: string
  kind: "CHAT" | "PROJECT"
  title: string | null
  mode: "plan" | "build" | "review"
  state: "active" | "interrupted" | "stopped" | "closed" | "archived"
  updated_at: string
  project_id: string | null
  project_root: string | null
  current_cwd: string | null
  git_branch: string | null
  last_active_at: string
  provider_id: string
  model_id: string
  permission_profile: "read-only" | "workspace" | "full-access"
  effective_permission_profile: "read-only" | "workspace" | "full-access"
  read_permission_profile?: "read-only" | "workspace" | "full-access"
  pinned_at?: string | null
}

export interface ProjectSummary {
  id: string
  root: string
  canonical_root: string
  name: string
  description: string
  pinned: boolean
  archived: boolean
  git_fingerprint: string | null
  created_at: string
  updated_at: string
  last_opened_at: string
  active_session_id?: string | null
}

export interface UsageSnapshot {
  model_calls: number
  tool_calls: number
  network_calls: number
  subagent_calls: number
  max_recursion_depth: number
  input_tokens: number
  output_tokens: number
  wall_time_s: number
  estimated_cost?: number | null
  exhausted: Array<string>
}

export interface GovernorSnapshot {
  execution: "automatic"
  recovery_attempts: number
  max_recovery_attempts: number
  compactions: number
  last_compacted_history_size: number
  context_pressure: number | null
  progress: Record<string, unknown> | null
}

export interface ProtocolError {
  code: string
  message: string
  retryable: boolean
  details: Record<string, unknown>
}

export interface QuestionOption {
  label: string
  description?: string
  recommended?: boolean
}

export interface UserQuestion {
  id: string
  title: string
  options?: Array<QuestionOption>
}

export interface QuestionRequest {
  request_id: string
  session_id: string
  turn_id: string
  status: "pending" | "answered" | "skipped" | "expired"
  questions: Array<UserQuestion>
  answers?: Record<string, string>
}

export interface FilePreview {
  path: string
  name: string
  content: string
  language: string
  size: number
  provenance?: "workspace" | "turn_changeset"
  changed_since_turn?: boolean
  sensitive?: boolean
}

export interface WebPreview {
  preview_id: string
  session_id: string
  url: string
  kind: "static" | "development"
  ready: boolean
  revision: number
  command?: string | null
  error?: string | null
}

export interface ToolAvailability {
  available: boolean | null
  reason: string
  requires: Array<string>
}

export interface ToolSummary {
  name: string
  description: string
  risk: string
  side_effects: string
  namespace: string
  capabilities: Array<string> | null
  permissions: Array<string> | null
  always_loaded: boolean
  availability?: ToolAvailability
  input_schema?: Record<string, unknown>
  output_schema?: Record<string, unknown> | null
  concurrency?: "serial" | "local-read"
}

export interface BrowserPage {
  target_id: string
  title: string
  url: string
}

export interface BrowserView {
  state: string
  session_id: string
  instance?: string
  image?: string
  url?: string
  target_id?: string
  error?: string
  pages?: Array<BrowserPage>
}

export interface ManagedProcess {
  id: string
  kind: string
  command: string
  cwd: string
  url?: string
  running: boolean
  can_stop: boolean
  pid?: number
  started_at?: number
  exit_code?: number | null
  generation?: number
  ended_at?: number | null
  exit_reason?: string | null
  readiness?: string
  readiness_checked_at?: number | null
}

export interface ProcessOutput {
  process: ManagedProcess
  stdout: string
  stderr: string
  truncated: boolean
}

export interface ViewedImage {
  uri: string
  name: string
  path: string
  width: number
  height: number
}

export interface AttachmentPreviewOptions {
  uri: string
  max_bytes?: number
  max_dimension?: number
}

export interface VisionSettings {
  mode: "automatic" | "dedicated" | "conversation"
  model_id: string | null
  confirm_unknown: boolean
  model_overrides?: Record<string, boolean>
  execution?: ModelExecutionSettings
}

export interface VisionActivity {
  vision_id: string
  route: "conversation" | "dedicated"
  provider_id: string
  model_id: string
  question: string
  images: Array<ViewedImage>
  analysis?: string
  artifact_uri?: string
  cached?: boolean
  error?: string
  model_name?: string
  provider_name?: string
  attempt_id?: number
  error_code?: string
  cache_key?: string
  origin?: string | null
  message_ref?: string | null
  tool_call_id?: string | null
  partial?: boolean
  stop_reason?: string
}

export interface VisualRouteStatus {
  available: boolean
  route: "conversation" | "dedicated" | "unavailable"
  reason: string
  model_id: string
  vision: boolean | null
  destination_model_id?: string | null
  destination_model?: string | null
  destination_provider?: string | null
}

export interface ModelExecutionSettings {
  max_concurrency: number
  providers: Record<string, number>
  models: Record<string, number>
  timeouts?: Record<string, number>
  provider_timeouts?: Record<string, Record<string, number>>
}

export interface ContextSettings {
  enabled: boolean
  compact_at_percent: number
  model_id: string | null
  model_windows: Record<string, number>
}

export interface ContextStatus {
  window_tokens: number
  window_source: "manual" | "override" | "provider" | "catalog" | "fallback"
  window_estimated: boolean
  total_window_tokens?: number
  max_context_tokens?: number | null
  max_input_tokens?: number | null
  max_output_tokens?: number | null
  limit_sources?: Record<string, unknown>
  discovered_at?: string | null
  metadata_updated_at?: string | null
  usable_input_tokens?: number
  output_reserve_tokens?: number
  compact_at_percent?: number
  compact_at_tokens?: number
  target_tokens?: number
  model_id?: string
  model_alias?: string
  provider_model_id?: string
  provider_id?: string
  provider_alias?: string
  session_id?: string
  compaction_enabled?: boolean
  projection_revision?: number
  last_request?: Record<string, unknown> | null
  last_compaction?: Record<string, unknown> | null
}

export interface ContextActivity {
  compaction_id: string
  session_id?: string
  turn_id?: string
  reason: "automatic" | "manual"
  status: "started" | "completed" | "skipped" | "failed" | "cancelled"
  window_tokens?: number
  window_source?: string
  used_tokens?: number
  after_tokens?: number
  usage_source?: string
  error?: string
  checks?: Record<string, unknown>
  duration_ms?: number
}

export interface ToolResultDelivery {
  result_id: string
  observation: string
  source_partial?: boolean
  delivery_partial?: boolean
  result_ref?: string | null
}

export interface MessageOrigin {
  kind: "user" | "peer" | "automation" | "schedule"
  message_id?: string | null
  source_session_id?: string | null
  source_turn_id?: string | null
  source_label?: string | null
  group_id?: string | null
  chain_id?: string | null
  hop?: number | null
  quoted_source?: Record<string, unknown> | null
  task_id?: string | null
  run_id?: string | null
  steer_id?: string | null
}

export interface PeerGroupMember {
  session_id: string
  label: string
  send: boolean
  receive: boolean
}

export interface PeerGroup {
  group_id: string
  board_id: string
  revision: number
  authorization_epoch: number
  enabled: boolean
  members: Array<PeerGroupMember>
}

export interface PeerMessage {
  message_id: string
  from_session_id?: string | null
  to_session_id: string
  group_id?: string | null
  chain_id?: string | null
  hop: number
  state: "queued" | "dispatching" | "running" | "completed" | "failed" | "cancelled" | "stopped" | "paused" | "uncertain"
  turn_id?: string | null
  display_message?: string | null
  origin: MessageOrigin
  error?: string | null
  created_at?: number | null
  updated_at?: number | null
}

export interface QueuedPromptEntry {
  message_id: string | null
  message: string
  state: "queued" | "paused" | "uncertain"
  origin: MessageOrigin
  error?: string | null
}

export interface BrowserTarget {
  target_id: string
  url: string
  title: string
  active: boolean
}

export interface BrowserContext {
  session_id: string
  supported: boolean
  host_registered: boolean
  context_state: "absent" | "creating" | "ready" | "disconnected" | "disposed"
  state?: string
  available?: boolean
  backend?: "electron-native" | null
  context_id?: string
  control?: "agent" | "user"
  control_revision?: number
  active_target_id?: string | null
  targets?: Array<BrowserTarget>
  control_state?: "agent" | "taking-user-control" | "user" | "uncertain"
}

export interface BrowserControl {
  control: "agent" | "user"
  control_revision: number
  control_state?: "agent" | "taking-user-control" | "user" | "uncertain"
  outstanding_mutations?: number
}

export interface FlowScope {
  kind: "project" | "session"
  id: string
  title: string
  root: string | null
}

export interface FlowExecutor {
  model: string
  calls: number
}

export interface FlowAgent {
  agent: string
  runs: number
}

export interface FlowSessionRef {
  session_id: string
  title: string
  turns: number
}

export interface FlowFile {
  path: string
  kind: string
  turn_id: string
}

export interface FlowVerification {
  passed: number
  failed: number
}

export interface FlowAnchor {
  session_id: string
  turn_id: string
}

export interface FlowStage {
  id: string
  index: number
  cycle_index: number
  kind: "planning" | "implementation" | "review"
  mode: string | null
  title: string
  excerpt: string
  status: "active" | "needs_you" | "done" | "failed" | "stopped"
  started_at: string
  completed_at: string | null
  duration_ms: number | null
  progress: number | null
  turns: number
  executors: Array<FlowExecutor>
  agents: Array<FlowAgent>
  sessions: Array<FlowSessionRef>
  files: Array<FlowFile>
  files_more: number
  verification: FlowVerification | null
  checkpoints: number
  origin_peer_turns: number
  anchor: FlowAnchor
  current_task_snapshot: FlowTasks | null
  turns_failed: number
  turns_stopped: number
  sessions_more: number
}

export interface FlowTasks {
  total: number
  done: number
  open: number
}

export interface FlowSummary {
  stages_total: number
  stages_done: number
  stages_active: number
  turns_total: number
  turns_failed: number
  files_changed: number
  tasks: FlowTasks | null
  progress: number | null
  started_at: string | null
  last_activity_at: string | null
  progress_coverage: Record<string, unknown>
}

export interface FlowResult {
  scope: FlowScope
  summary: FlowSummary
  stages: Array<FlowStage>
  revision: string
  truncated: boolean
  stages_omitted: number
  next_cursor: string | null
}

export interface ProviderPreset {
  id: string
  name: string
  provider_type: string
  endpoint: string
  auth_methods: Array<string>
  experimental: boolean
  enabled: boolean
  local: boolean
}

export interface ProviderUsageWindow {
  id: string
  label: string
  scope: string
  used_percent: number | null
  remaining_percent: number | null
  resets_at: string | null
  duration_seconds: number | null
}

export interface ProviderBalance {
  scope: string
  label: string
  currency: string
  remaining: string | null
  limit: string | null
  unlimited: boolean
  granted?: string | null
  topped_up?: string | null
}

export interface ProviderUsageSnapshot {
  provider_id: string
  product_id: string
  status: "available" | "partial" | "stale" | "unsupported" | "needs_auth" | "error"
  windows: Array<ProviderUsageWindow>
  balances: Array<ProviderBalance>
  fetched_at: string | null
  source: string | null
  detail: string
  retry_at: string | null
  dashboard_url?: string | null
  local_usage?: ProviderLocalUsage
}

export interface ProviderAuthSnapshot {
  operation_id: string | null
  authorization_url: string | null
  user_code: string | null
  provider_id: string
  status: "disconnected" | "waiting" | "connected" | "refreshing" | "needs_auth" | "cancelled" | "expired" | "error"
  expires_at: number | null
  detail: string
}

export interface ProviderLocalUsage {
  calls: number
  input_tokens: number | null
  output_tokens: number | null
}

export interface ProviderIdentity {
  product_id: string
  product_name: string
  experimental: boolean
  model_count: number
  updated_at?: string
}

export interface TurnTokenUsage {
  input_tokens: number
  output_tokens: number
  total_tokens: number
  model_calls: number
  revision: number
  cached_input_tokens?: number | null
  reasoning_tokens?: number | null
  source: "estimated" | "mixed" | "reported"
  phase: "thinking" | "streaming" | "settled"
  context_tokens?: number
}
