#!/usr/bin/env node
// Inventario Electron posterior al cutover H.
//
// El contrato capturado de la última build Tauri 0.1.3 es una entrada histórica
// inmutable. Este generador produce la allowlist del renderer y la traducción
// Electron -> Engine, y falla si aparece una llamada desconocida, un adaptador
// manual ausente o una dependencia Tauri en la aplicación activa.

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const CHECK = process.argv.includes('--check')
const CONTRACT_PATH = join(ROOT, 'docs/migration/desktop-command-contract.json')
const contract = JSON.parse(readFileSync(CONTRACT_PATH, 'utf8'))
const commands = [...contract.commands].sort((a, b) => a.command.localeCompare(b.command))
const hostOnly = commands.filter((row) => !row.engine_method).map((row) => row.command)
const engineBacked = commands.filter((row) => row.engine_method).map((row) => row.command)
const all = commands.map((row) => row.command)

function walk(dir, out = []) {
  if (!existsSync(dir)) return out
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) walk(path, out)
    else out.push(path)
  }
  return out
}

const rel = (path) => relative(ROOT, path).replaceAll('\\', '/')
const quoteUnion = (values) => values.map((value) => `  | ${JSON.stringify(value)}`).join('\n')
const quoteList = (values) => values.map((value) => `  ${JSON.stringify(value)},`).join('\n')

const commandsTs = `// @generated by scripts/desktop-parity.mjs — DO NOT EDIT.\n// Source: docs/migration/desktop-command-contract.json (Tauri 0.1.3 contract).\n\nexport type DesktopCommand =\n${quoteUnion(all)}\n\nexport const DESKTOP_COMMANDS: readonly DesktopCommand[] = [\n${quoteList(all)}\n] as const\n\nexport type HostOnlyCommand =\n${quoteUnion(hostOnly)}\n\nexport const HOST_ONLY_COMMANDS: readonly HostOnlyCommand[] = [\n${quoteList(hostOnly)}\n] as const\n\nexport type EngineBackedCommand = Exclude<DesktopCommand, HostOnlyCommand>\n\nexport const ENGINE_BACKED_COMMANDS: readonly EngineBackedCommand[] = [\n${quoteList(engineBacked)}\n] as const\n`

const mapRows = commands.filter((row) => row.engine_method).map((row) => {
  const normalizeFallback = (value) => value === 'false' ? false : value === 'true' ? true : value
  const value = {
    method: row.engine_method,
    params: (row.engine_params ?? []).map(({ default: fallback, ...binding }) => ({
      ...binding,
      ...(fallback !== undefined ? { fallback: normalizeFallback(fallback) } : {}),
    })),
    ...(row.passthrough ? { passthrough: row.passthrough } : {}),
    ...(row.manual ? { manual: true } : {}),
  }
  return `  ${JSON.stringify(row.command)}: ${JSON.stringify(value)},`
}).join('\n')

const mapTs = `// @generated by scripts/desktop-parity.mjs — DO NOT EDIT.\n// Source: docs/migration/desktop-command-contract.json (Tauri 0.1.3 contract).\n\nexport interface ParamBinding {\n  key: string\n  from: string | null\n  optional: boolean\n  fallback?: boolean | string\n}\n\nexport interface CommandTranslation {\n  method: string\n  params: ParamBinding[]\n  passthrough?: string\n  manual?: true\n}\n\nexport const COMMAND_MAP: Record<string, CommandTranslation> = {\n${mapRows}\n}\n`

const sourceFiles = walk(join(ROOT, 'src')).filter((path) => /\.[cm]?[jt]sx?$/.test(path) && !/\.test\.[jt]sx?$/.test(path))
const callers = new Map(all.map((name) => [name, []]))
const unknownCalls = []
const tauriLeaks = []
for (const path of sourceFiles) {
  const text = readFileSync(path, 'utf8')
  if (/\b(?:from\s+|import\s*\()['\"]@tauri-apps\//.test(text)) tauriLeaks.push(rel(path))
  for (const match of text.matchAll(/\.command(?:<[^;]*?>)?\(\s*['"]([a-z0-9_]+)['"]/g)) {
    const name = match[1]
    if (!callers.has(name)) unknownCalls.push({ command: name, caller: rel(path) })
    else callers.get(name).push(rel(path))
  }
}

const adapters = readFileSync(join(ROOT, 'electron/main/engine/commandAdapters.ts'), 'utf8')
const missingAdapters = commands
  .filter((row) => row.manual && !new RegExp(`\\b${row.command}\\s*:`).test(adapters))
  .map((row) => row.command)
const rootPackage = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))
const tauriPackages = [...Object.keys(rootPackage.dependencies ?? {}), ...Object.keys(rootPackage.devDependencies ?? {})]
  .filter((name) => name.startsWith('@tauri-apps/'))
const forbiddenPaths = ['src-tauri', 'src/platform/tauri.ts'].filter((path) => existsSync(join(ROOT, path)))

const inventory = {
  schema: 'rinari.desktop-parity.electron.v1',
  contract_source: rel(CONTRACT_PATH),
  captured_commit: contract.captured_commit,
  commands: commands.map((row) => ({
    command: row.command,
    kind: row.engine_method ? 'engine' : 'host',
    method: row.engine_method ?? null,
    manual: row.manual,
    callers: [...new Set(callers.get(row.command))].sort(),
  })),
  summary: {
    commands: all.length,
    engine_backed: engineBacked.length,
    host_only: hostOnly.length,
    manual_adapters: commands.filter((row) => row.manual).length,
    without_callers: commands.filter((row) => callers.get(row.command).length === 0).length,
  },
}

const mdRows = inventory.commands.map((row) =>
  `| \`${row.command}\` | ${row.kind} | ${row.method ? `\`${row.method}\`` : '—'} | ${row.callers.length ? row.callers.map((item) => `\`${item}\``).join('<br>') : '**ninguno**'} |`,
).join('\n')
const inventoryMd = `# Paridad desktop Electron\n\nInventario posterior al cutover H. La fuente de compatibilidad es el contrato\ncapturado de Tauri 0.1.3; el runtime activo y todas las llamadas del producto\nson Electron.\n\n- Comandos: **${all.length}**\n- Respaldados por Engine: **${engineBacked.length}**\n- Resueltos por el host: **${hostOnly.length}**\n- Adaptadores manuales fail-closed: **${inventory.summary.manual_adapters}**\n- Imports Tauri activos: **0**\n\n| Comando | Dueño | Método Engine | Llamadores |\n|---|---|---|---|\n${mdRows}\n`

const outputs = [
  [join(ROOT, 'src/platform/commands.generated.ts'), commandsTs],
  [join(ROOT, 'electron/main/engine/commandMap.generated.ts'), mapTs],
  [join(ROOT, 'docs/migration/desktop-parity.json'), `${JSON.stringify(inventory, null, 2)}\n`],
  [join(ROOT, 'docs/migration/desktop-parity.md'), inventoryMd],
]

const errors = []
if (unknownCalls.length) errors.push(`unknown command calls: ${JSON.stringify(unknownCalls)}`)
if (missingAdapters.length) errors.push(`missing manual adapters: ${missingAdapters.join(', ')}`)
if (tauriLeaks.length) errors.push(`Tauri imports in active source: ${tauriLeaks.join(', ')}`)
if (tauriPackages.length) errors.push(`Tauri packages in root package.json: ${tauriPackages.join(', ')}`)
if (forbiddenPaths.length) errors.push(`active Tauri paths remain: ${forbiddenPaths.join(', ')}`)

for (const [path, content] of outputs) {
  if (CHECK) {
    if (!existsSync(path) || readFileSync(path, 'utf8').replaceAll('\r\n', '\n') !== content) {
      errors.push(`${rel(path)} is stale; run npm run parity:inventory`)
    }
  } else {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, content)
  }
}

if (errors.length) {
  for (const error of errors) console.error(error)
  process.exit(1)
}
console.log(`commands: ${all.length} | engine: ${engineBacked.length} | host: ${hostOnly.length} | unresolved: 0`)
